### ISSUE TITLE
How to ...?

### ISSUE THREAD

**Issue by fmohican** [morsisko/NosTaleRPC#1]
Hi!
I just compile the dll, but how to use?

**Comment by fmohican** [comment]
@morsisko

**Comment by morsisko** [comment]
Hi, unfortunately the addresses are out of date, abstracting from this you need to build the .DLL and then copy it, along with the discord-rpc.dll to your game folder, then use eg. Cheat Engine to inject it into game

**Comment by fmohican** [comment]
so? can you update? or something?


btw: Thanks for anwser

**Comment by morsisko** [comment]
Maybe in the free time I will update it, but nothing to promise

**Comment by fmohican** [comment]
Okay, thanks you!
